codigo|titulo|anio|genero|sinopsis|director|actores|restriccion|duracion|formato|poster|proveedor
102899|Ant-Man|2015|Science Fiction|Armed with the astonishing ability to shrink in scale but increase in strength, con-man Scott Lang must embrace his inner-hero and help his mentor, Dr. Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.|Peyton Reed|Paul Rudd,Michael Douglas,Evangeline Lilly|No|115|3D|http://image.tmdb.org/t/p/w500/D6e8RJf2qUstnfkTslTXNTUAlT.jpg|2
140607|Star Wars: Episode VII - The Force Awakens|2015|Action|A continuation of the saga created by George Lucas and set thirty years after Star Wars: Episode VI - Return of the Jedi (1983).|J.J. Abrams|Adam Driver,Oscar Isaac,Harrison Ford|No|136|2D|http://image.tmdb.org/t/p/w500/fYzpM9GmpBlIC893fNjoWCwE24H.jpg|1
135397|Jurassic World|2015|Action|Twenty-two years after the events of Jurassic Park, Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.|Colin Trevorrow|Chris Pratt,Bryce Dallas Howard,Jake Johnson|No|124|2D|http://image.tmdb.org/t/p/w500/jjBgi2r5cRt36xF6iNUEhzscEcb.jpg|1
211672|Minions|2015|Family|Minions Stuart, Kevin and Bob are recruited by Scarlet Overkill, a super-villain who, alongside her inventor husband Herb, hatches a plot to take over the world.|Kyle Balda|Sandra Bullock,Jon Hamm,Michael Keaton|No|91|2D|http://image.tmdb.org/t/p/w500/s5uMY8ooGRZOL0oe4sIvnlTsYQO.jpg|1
76341|Mad Max: Fury Road|2015|Thriller|An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order. There's Max, a man of action and a man of few words, who seeks peace of mind following the loss of his wife and child in the aftermath of the chaos. And Furiosa, a woman of action and a woman who believes her path to survival may be achieved if she can make it across the desert back to her childhood homeland.|George Miller|Tom Hardy,Charlize Theron,Hugh Keays-Byrne|No|120|2D|http://image.tmdb.org/t/p/w500/kqjL17yufvn9OVLyXYpvtyrFfak.jpg|1
87101|Terminator Genisys|2015|Science Fiction|The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.|Alan Taylor|Arnold Schwarzenegger,Jason Clarke,Emilia Clarke|No|125|2D|http://image.tmdb.org/t/p/w500/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg|2
166424|Fantastic Four|2015|Action|Four young outsiders teleport to a dangerous universe, which alters their physical form in shocking ways. Their lives irrevocably upended, the team must learn to harness their daunting new abilities and work together to save Earth from a former friend turned enemy.|Josh Trank|Miles Teller,Michael B. Jordan,Kate Mara|No|100|2D|http://image.tmdb.org/t/p/w500/g23cs30dCMiG4ldaoVNP1ucjs6.jpg|1
131634|The Hunger Games: Mockingjay - Part 2|2015|Drama|With the nation of Panem in a full scale war, Katniss confronts President Snow in the final showdown. Teamed with a group of her closest friends – including Gale, Finnick, and Peeta – Katniss goes off on a mission with the unit from District 13 as they risk their lives to stage an assassination attempt on President Snow who has become increasingly obsessed with destroying her. The mortal traps, enemies, and moral choices that await Katniss will challenge her more than any arena she faced in The Hunger Games.|Francis Lawrence|Jennifer Lawrence,Josh Hutcherson,Liam Hemsworth|No|136|2D|http://image.tmdb.org/t/p/w500/nN4cEJMHJHbJBsp3vvvhtNWLGqg.jpg|1
157336|Interstellar|2014|Drama|Interstellar chronicles the adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.|Christopher Nolan|Matthew McConaughey,Anne Hathaway,Jessica Chastain|No|169|3D|http://image.tmdb.org/t/p/w500/nBNZadXqJSdt05SHLqgT0HuC5Gm.jpg|1
122917|The Hobbit: The Battle of the Five Armies|2014|Adventure|Immediately after the events of The Desolation of Smaug, Bilbo and the dwarves try to defend Erebor's mountain of treasure from others who claim it: the men of the ruined Laketown and the elves of Mirkwood. Meanwhile an army of Orcs led by Azog the Defiler is marching on Erebor, fueled by the rise of the dark lord Sauron. Dwarves, elves and men must unite, and the hope for Middle-Earth falls into Bilbo's hands.|Peter Jackson|Martin Freeman,Ian McKellen,Richard Armitage|No|144|2D|http://image.tmdb.org/t/p/w500/vgAHvS0bT3fpcpnJqT6uDTUsHTo.jpg|1
214756|Ted 2|2015|Comedy|Newlywed couple Ted and Tami-Lynn want to have a baby, but in order to qualify to be a parent, Ted will have to prove he's a person in a court of law.|Seth MacFarlane|Mark Wahlberg,Seth MacFarlane,Amanda Seyfried|No|115|2D|http://image.tmdb.org/t/p/w500/A7HtCxFe7Ms8H7e7o2zawppbuDT.jpg|2
286217|The Martian|2015|Drama|During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.|Ridley Scott|Matt Damon,Jessica Chastain,Kate Mara|No|141|2D|http://image.tmdb.org/t/p/w500/5aGhaIHYuQbqlHWvWYqMCnj40y2.jpg|1
257344|Pixels|2015|Action|Video game experts are recruited by the military to fight 1980s-era video game characters who've attacked New York.|Chris Columbus|Adam Sandler,Michelle Monaghan,Peter Dinklage|No|105|2D|http://image.tmdb.org/t/p/w500/ktyVmIqfoaJ8w0gDSZyjhhOPpD6.jpg|1
131631|The Hunger Games: Mockingjay - Part 1|2014|Science Fiction|Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.|Francis Lawrence|Jennifer Lawrence,Josh Hutcherson,Liam Hemsworth|No|123|2D|http://image.tmdb.org/t/p/w500/cWERd8rgbw7bCMZlwP207HUXxym.jpg|1
177677|Mission: Impossible – Rogue Nation|2015|Action|Ethan and team take on their most impossible mission yet, eradicating the Syndicate - an International rogue organization as highly skilled as they are, committed to destroying the IMF.|Christopher McQuarrie|Tom Cruise,Jeremy Renner,Simon Pegg|No|131|2D|http://image.tmdb.org/t/p/w500/z2sJd1OvAGZLxgjBdSnQoLCfn3M.jpg|1
205775|In the Heart of the Sea|2015|Adventure|In the winter of 1820, the New England whaling ship Essex was assaulted by something no one could believe: a whale of mammoth size and will, and an almost human sense of vengeance.  The real-life maritime disaster would inspire Herman Melville’s Moby-Dick.  But that told only half the story.  “Heart of the Sea” reveals the encounter’s harrowing aftermath, as the ship’s surviving crew is pushed to their limits and forced to do the unthinkable to stay alive.  Braving storms, starvation, panic and despair, the men will call into question their deepest beliefs, from the value of their lives to the morality of their trade, as their captain searches for direction on the open sea and his first mate still seeks to bring the great whale down.|Ron Howard|Chris Hemsworth,Cillian Murphy,Benjamin Walker|No|121|2D|http://image.tmdb.org/t/p/w500/uekIGnzTACciWrfR7jOuof7xHgR.jpg|2
198663|The Maze Runner|2014|Action|"Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow ""runners"" for a shot at escape."|Wes Ball|Dylan O'Brien,Aml Ameen,Ki Hong Lee|No|113|3D|http://image.tmdb.org/t/p/w500/coss7RgL0NH6g4fC2s5atvf3dFO.jpg|1
11|Star Wars|1977|Adventure|Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.|George Lucas|Mark Hamill,Harrison Ford,Carrie Fisher|No|121|2D|http://image.tmdb.org/t/p/w500/tvSlBzAdRE29bZe5yYWrJ2ds137.jpg|1
206647|Spectre|2015|Action|A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.|Sam Mendes|Daniel Craig,Christoph Waltz,Léa Seydoux|No|148|2D|http://image.tmdb.org/t/p/w500/mSvpKOWbyFtLro9BjfEGqUw5dXE.jpg|1
254128|San Andreas|2015|Action|In the aftermath of a massive earthquake in California, a rescue-chopper pilot makes a dangerous journey across the state in order to rescue his estranged daughter.|Brad Peyton|Alexandra Daddario,Dwayne Johnson,Carla Gugino|No|114|2D|http://image.tmdb.org/t/p/w500/qey0tdcOp9kCDdEZuJ87yE3crSe.jpg|1
150540|Inside Out|2015|Comedy|Growing up can be a bumpy road, and it's no exception for Riley, who is uprooted from her Midwest life when her father starts a new job in San Francisco. Like all of us, Riley is guided by her emotions - Joy, Fear, Anger, Disgust and Sadness. The emotions live in Headquarters, the control center inside Riley's mind, where they help advise her through everyday life. As Riley and her emotions struggle to adjust to a new life in San Francisco, turmoil ensues in Headquarters. Although Joy, Riley's main and most important emotion, tries to keep things positive, the emotions conflict on how best to navigate a new city, house and school.|Pete Docter|Amy Poehler,Phyllis Smith,Richard Kind|No|94|2D|http://image.tmdb.org/t/p/w500/aAmfIX3TT40zUHGcCKrlOZRKC7u.jpg|2
294254|Maze Runner: The Scorch Trials|2015|Thriller|Thomas and his fellow Gladers face their greatest challenge yet: searching for clues about the mysterious and powerful organization known as WCKD. Their journey takes them to the Scorch, a desolate landscape filled with unimaginable obstacles. Teaming up with resistance fighters, the Gladers take on WCKD’s vastly superior forces and uncover its shocking plans for them all.|Wes Ball|Dylan O'Brien,Kaya Scodelario,Thomas Brodie-Sangster|No|132|2D|http://image.tmdb.org/t/p/w500/vlTPQANjLYTebzFJM1G4KeON0cb.jpg|1
99861|Avengers: Age of Ultron|2015|Action|When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.|Joss Whedon|Robert Downey Jr.,Chris Evans,Chris Hemsworth|No|141|2D|http://image.tmdb.org/t/p/w500/t90Y3G8UGQp0f0DrP60wRu9gfrH.jpg|1
271718|Trainwreck|2015|Romance|Having thought that monogamy was never possible, a commitment-phobic career woman may have to face her fears when she meets a good guy.|Judd Apatow|Amy Schumer,Bill Hader,Brie Larson|No|125|2D|http://image.tmdb.org/t/p/w500/e5jbaEiWYHtstuHPHl3lGPoRs4c.jpg|1
118340|Guardians of the Galaxy|2014|Science Fiction|Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.|James Gunn|Chris Pratt,Zoe Saldana,Dave Bautista|No|121|3D|http://image.tmdb.org/t/p/w500/y31QB9kn3XSudA15tV7UWQ9XLuW.jpg|1
312221|Creed|2015|Drama|The former World Heavyweight Champion Rocky Balboa serves as a trainer and mentor to Adonis Johnson, the son of his late friend and former rival Apollo Creed.|Ryan Coogler|Michael B. Jordan,Sylvester Stallone,Graham McTavish|No|132|2D|http://image.tmdb.org/t/p/w500/xSE4NBFDzqedwa4AIj99r1Z7ljF.jpg|2
203801|The Man from U.N.C.L.E.|2015|Comedy|At the height of the Cold War, a mysterious criminal organization plans to use nuclear weapons and technology to upset the fragile balance of power between the United States and Soviet Union. CIA agent Napoleon Solo and KGB agent Illya Kuryakin are forced to put aside their hostilities and work together to stop the evildoers in their tracks. The duo's only lead is the daughter of a missing German scientist, whom they must find soon to prevent a global catastrophe.|Guy Ritchie|Henry Cavill,Armie Hammer,Alicia Vikander|No|116|2D|http://image.tmdb.org/t/p/w500/5ttOaThDVmTpV8iragbrhdfxEep.jpg|1
205596|The Imitation Game|2014|History|Based on the real life story of legendary cryptanalyst Alan Turing, the film portrays the nail-biting race against time by Turing and his brilliant team of code-breakers at Britain's top-secret Government Code and Cypher School at Bletchley Park, during the darkest days of World War II.|Morten Tyldum|Benedict Cumberbatch,Keira Knightley,Matthew Goode|No|113|2D|http://image.tmdb.org/t/p/w500/noUp0XOqIcmgefRnRZa1nhtRvWO.jpg|1
177572|Big Hero 6|2014|Adventure|The special bond that develops between plus-sized inflatable robot Baymax, and prodigy Hiro Hamada, who team up with a group of friends to form a band of high-tech heroes.|Don Hall|Scott Adsit,Ryan Potter,Daniel Henney|No|102|2D|http://image.tmdb.org/t/p/w500/3zQvuSAUdC3mrx9vnSEpkFX0968.jpg|1
262500|Insurgent|2015|Adventure|Beatrice Prior must confront her inner demons and continue her fight against a powerful alliance which threatens to tear her society apart.|Robert Schwentke|Shailene Woodley,Theo James,Kate Winslet|No|119|2D|http://image.tmdb.org/t/p/w500/aBBQSC8ZECGn6Wh92gKDOakSC8p.jpg|1
245891|John Wick|2014|Action|After the sudden death of his beloved wife, John Wick receives one last gift from her, a beagle puppy named Daisy, and a note imploring him not to forget how to love. But John's mourning is interrupted when his 1969 Boss Mustang catches the eye of sadistic thug Iosef Tarasov who breaks into his house and steals it, beating John unconscious in the process. Unwittingly, he has just reawakened one of the most brutal assassins the underworld has ever known.|Chad Stahelski|Keanu Reeves,Michael Nyqvist,Alfie Allen|No|101|2D|http://image.tmdb.org/t/p/w500/5vHssUeVe25bMrof1HyaPyWgaP.jpg|2
158852|Tomorrowland|2015|Fantasy|"Bound by a shared destiny, a bright, optimistic teen bursting with scientific curiosity and a former boy-genius inventor jaded by disillusionment embark on a danger-filled mission to unearth the secrets of an enigmatic place somewhere in time and space that exists in their collective memory as ""Tomorrowland."""|Brad Bird|Britt Robertson,George Clooney,Raffey Cassidy|No|130|2D|http://image.tmdb.org/t/p/w500/69Cz9VNQZy39fUE2g0Ggth6SBTM.jpg|1
296098|Bridge of Spies|2015|Thriller|An American lawyer is recruited by the CIA during the Cold War to help rescue a pilot detained in the Soviet Union.|Steven Spielberg|Tom Hanks,Austin Stowell,Eve Hewson|No|141|3D|http://image.tmdb.org/t/p/w500/AcuW0ITY1WElLzIoiA6PpPCsGwm.jpg|1
194662|Birdman|2014|Drama|A fading actor best known for his portrayal of a popular superhero attempts to mount a comeback by appearing in a Broadway play. As opening night approaches, his attempts to become more altruistic, rebuild his career, and reconnect with friends and family prove more difficult than expected.|Alejandro González Iñárritu|Michael Keaton,Zach Galifianakis,Edward Norton|No|119|2D|http://image.tmdb.org/t/p/w500/rSZs93P0LLxqlVEbI001UKoeCQC.jpg|1
98566|Teenage Mutant Ninja Turtles|2014|Science Fiction|The city needs heroes. Darkness has settled over New York City as Shredder and his evil Foot Clan have an iron grip on everything from the police to the politicians. The future is grim until four unlikely outcast brothers rise from the sewers and discover their destiny as Teenage Mutant Ninja Turtles. The Turtles must work with fearless reporter April and her wise-cracking cameraman Vern Fenwick to save the city and unravel Shredder's diabolical plan.|Jonathan Liebesman|Megan Fox,Will Arnett,William Fichtner|No|101|2D|http://image.tmdb.org/t/p/w500/oDL2ryJ0sV2bmjgshVgJb3qzvwp.jpg|1
244786|Whiplash|2014|Music|Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.|Damien Chazelle|Miles Teller,J.K. Simmons,Melissa Benoist|No|105|2D|http://image.tmdb.org/t/p/w500/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg|2
207703|Kingsman: The Secret Service|2015|Crime|Kingsman: The Secret Service tells the story of a super-secret spy organization that recruits an unrefined but promising street kid into the agency's ultra-competitive training program just as a global threat emerges from a twisted tech genius.|Matthew Vaughn|Taron Egerton,Colin Firth,Samuel L. Jackson|No|130|2D|http://image.tmdb.org/t/p/w500/8x7ej0LnHdKUqilNNJXYOeyB6L9.jpg|1
100402|Captain America: The Winter Soldier|2014|Action|After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.|Joe Russo|Chris Evans,Scarlett Johansson,Sebastian Stan|No|136|2D|http://image.tmdb.org/t/p/w500/5TQ6YDmymBpnF005OyoB7ohZps9.jpg|1
198184|Chappie|2015|Action|Every child comes into the world full of promise, and none more so than Chappie: he is gifted, special, a prodigy. Like any child, Chappie will come under the influence of his surroundings—some good, some bad—and he will rely on his heart and soul to find his way in the world and become his own man. But there's one thing that makes Chappie different from any one else: he is a robot.|Neill Blomkamp|Sharlto Copley,Dev Patel,Ninja|No|120|2D|http://image.tmdb.org/t/p/w500/saF3HtAduvrP9ytXDxSnQJP3oqx.jpg|1
242582|Nightcrawler|2014|Crime|A driven young man (Gyllenhaal) stumbles upon the underground world of L.A. freelance crime journalism.  When Lou Bloom, desperate for work, muscles into the world of L.A. crime journalism, he blurs the line between observer and participant to become the star of his own story. Aiding him in his effort is Nina, a TV-news veteran.|Dan Gilroy|Jake Gyllenhaal,Bill Paxton,Rene Russo|No|117|2D|http://image.tmdb.org/t/p/w500/fukWJhLISH7f6cnYSdgb0JrSP2Q.jpg|1
249070|Hitman: Agent 47|2015|Action|An assassin teams up with a woman to help her find her father and uncover the mysteries of her ancestry.|Aleksander Bach|Rupert Friend,Zachary Quinto,Hannah Ware|No|96|3D|http://image.tmdb.org/t/p/w500/4VmZeT8YkuMI6BrA623mHZDISlN.jpg|2
168259|Furious 7|2015|Action|Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.|James Wan|Vin Diesel,Paul Walker,Jason Statham|No|140|2D|http://image.tmdb.org/t/p/w500/dCgm7efXDmiABSdWDHBDBx2jwmn.jpg|1
228150|Fury|2014|War|"Last months of World War II in April 1945. As the Allies make their final push in the European Theater, a battle-hardened U.S. Army sergeant in the 2nd Armored Division named Wardaddy commands a Sherman tank called ""Fury"" and its five-man crew on a deadly mission behind enemy lines. Outnumbered and outgunned, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany."|David Ayer|Brad Pitt,Shia LaBeouf,Logan Lerman|No|135|2D|http://image.tmdb.org/t/p/w500/fIHF63oznk2PXlYM6pPfhnOB3SD.jpg|1
260346|Taken 3|2015|Crime|Ex-government operative Bryan Mills finds his life is shattered when he's falsely accused of a murder that hits close to home. As he's pursued by a savvy police inspector, Mills employs his particular set of skills to track the real killer and exact his unique brand of justice.|Olivier Megaton|Liam Neeson,Forest Whitaker,Famke Janssen|No|109|2D|http://image.tmdb.org/t/p/w500/ikDwR3i2bczqnRf1urJTy77YTFf.jpg|1
1893|Star Wars: Episode I - The Phantom Menace|1999|Adventure|Anakin Skywalker, a young slave strong with the Force, is discovered on Tatooine. Meanwhile, the evil Sith have returned, enacting their plot for revenge against the Jedi.|George Lucas|Liam Neeson,Ewan McGregor,Natalie Portman|No|136|2D|http://image.tmdb.org/t/p/w500/n8V09dDc02KsSN6Q4hC2BX6hN8X.jpg|1
127585|X-Men: Days of Future Past|2014|Action|The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as they join forces with their younger selves in an epic battle that must change the past – to save our future.|Bryan Singer|Hugh Jackman,James McAvoy,Patrick Stewart|No|131|2D|http://image.tmdb.org/t/p/w500/qKkFk9HELmABpcPoc1HHZGIxQ5a.jpg|2
49026|The Dark Knight Rises|2012|Action|Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.|Christopher Nolan|Christian Bale,Michael Caine,Gary Oldman|No|165|2D|http://image.tmdb.org/t/p/w500/dEYnvnUfXrqvqeRSqvIEtmzhoA8.jpg|1
307081|Southpaw|2015|Action|"Billy ""The Great"" Hope, the reigning junior middleweight boxing champion, has an impressive career, a loving wife and daughter, and a lavish lifestyle. However, when tragedy strikes, Billy hits rock bottom, losing his family, his house and his manager. He soon finds an unlikely savior in Tick Willis, a former fighter who trains the city's toughest amateur boxers. With his future on the line, Hope fights to reclaim the trust of those he loves the most."|Antoine Fuqua|Jake Gyllenhaal,Rachel McAdams,Forest Whitaker|No|123|2D|http://image.tmdb.org/t/p/w500/z3nGs7UED9XlqUkgWeT4jQ80m1N.jpg|1
150689|Cinderella|2015|Romance|When her father unexpectedly passes away, young Ella finds herself at the mercy of her cruel stepmother and her daughters. Never one to give up hope, Ella's fortunes begin to change after meeting a dashing stranger in the woods.|Kenneth Branagh|Lily James,Cate Blanchett,Richard Madden|No|112|3D|http://image.tmdb.org/t/p/w500/2i0JH5WqYFqki7WDhUW56Sg0obh.jpg|1
49017|Dracula Untold|2014|Horror|Vlad Tepes is a great hero, but when he learns the Sultan is preparing for battle and needs to form an army of 1,000 boys, including Vlad's son, he vows to find a way to protect his family. Vlad turns to dark forces in order to get the power to destroy his enemies and agrees to go from hero to monster as he's turned into the mythological vampire Dracula.|Gary Shore|Luke Evans,Sarah Gadon,Dominic Cooper|No|92|2D|http://image.tmdb.org/t/p/w500/4oy4e0DP6LRwRszfx8NY8EYBj8V.jpg|1
955|Mission: Impossible II|2000|Adventure|With computer genius Luther Stickell at his side and a beautiful thief on his mind, agent Ethan Hunt races across Australia and Spain to stop a former IMF agent from unleashing a genetically engineered biological weapon called Chimera. This mission, should Hunt choose to accept it, plunges him into the center of an international crisis of terrifying magnitude.|John Woo|Tom Cruise,Dougray Scott,Thandie Newton|No|123|2D|http://image.tmdb.org/t/p/w500/3XcpeZeSHlDjdPFTWyCvDM1bL6z.jpg|2
105864|The Good Dinosaur|2015|Fantasy|An epic journey into the world of dinosaurs where an Apatosaurus named Arlo makes an unlikely human friend.|Peter Sohn|Jeffrey Wright,Frances McDormand,Maleah Nipay-Padilla|No|101|2D|http://image.tmdb.org/t/p/w500/2ZckiMTfSkCep2JTtZbr73tnQbN.jpg|1
201088|Blackhat|2015|Mystery|A man is released from prison to help American and Chinese authorities pursue a mysterious cyber criminal. The dangerous search leads them from Chicago to Hong Kong.|Michael Mann|Chris Hemsworth,Leehom Wang,Tang Wei|No|133|2D|http://image.tmdb.org/t/p/w500/sW3VEsulmxMlOmQwm0h7H7lZROi.jpg|1
238615|Self/less|2015|Mystery|An extremely wealthy elderly man dying from cancer undergoes a radical medical procedure that transfers his consciousness to the body of a healthy young man but everything may not be as good as it seems when he starts to uncover the mystery of the body's origins and the secret organization that will kill to keep its secrets.|Tarsem Singh|Ryan Reynolds,Ben Kingsley,Natalie Martinez|No|116|2D|http://image.tmdb.org/t/p/w500/5MUyULSD4syaMQFcfPABqopAO4e.jpg|1
534|Terminator Salvation|2009|Drama|All grown up in post-apocalyptic 2018, John Connor must lead the resistance of humans against the increasingly dominating militaristic robots. But when Marcus Wright appears, his existence confuses the mission as Connor tries to determine whether Wright has come from the future or the past -- and whether he's friend or foe.|McG|Christian Bale,Sam Worthington,Anton Yelchin|No|115|2D|http://image.tmdb.org/t/p/w500/hxDfhavtxA2Ayx7O9BsQMcZRdG0.jpg|1
24428|The Avengers|2012|Science Fiction|When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!|Joss Whedon|Robert Downey Jr.,Chris Evans,Mark Ruffalo|No|143|2D|http://image.tmdb.org/t/p/w500/cezWGskPY5x7GaglTTRN4Fugfb8.jpg|2
57158|The Hobbit: The Desolation of Smaug|2013|Adventure|The Dwarves, Bilbo and Gandalf have successfully escaped the Misty Mountains, and Bilbo has gained the One Ring. They all continue their journey to get their gold back from the Dragon, Smaug.|Peter Jackson|Martin Freeman,Ian McKellen,Richard Armitage|No|161|3D|http://image.tmdb.org/t/p/w500/gQCiuxGsfiXH1su6lp9n0nd0UeH.jpg|1
76757|Jupiter Ascending|2015|Science Fiction|In a universe where human genetic material is the most precious commodity, an impoverished young Earth woman becomes the key to strategic maneuvers and internal strife within a powerful dynasty…|Lana Wachowski|Mila Kunis,Channing Tatum,Sean Bean|No|124|2D|http://image.tmdb.org/t/p/w500/aMEsvTUklw0uZ3gk3Q6lAj6302a.jpg|1
210577|Gone Girl|2014|Mystery|With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.|David Fincher|Ben Affleck,Rosamund Pike,Tyler Perry|No|145|2D|http://image.tmdb.org/t/p/w500/gdiLTof3rbPDAmPaCf4g6op46bj.jpg|1
68718|Django Unchained|2012|Drama|With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.|Quentin Tarantino|Jamie Foxx,Christoph Waltz,Leonardo DiCaprio|No|165|2D|http://image.tmdb.org/t/p/w500/5WJnxuw41sddupf8cwOxYftuvJG.jpg|1
